services:
  postgres:
    image: postgres:16
    container_name: alert-mns-postgres
    environment:
      POSTGRES_DB: alertmns
      POSTGRES_USER: alertmns
      POSTGRES_PASSWORD: alertmns
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: