server:
  servlet:
    session:
      timeout: 8h
      cookie:
        http-only: true
        same-site: lax
        secure: ${SESSION_COOKIE_SECURE:false}

alertmns:
  bootstrap:
    enabled: true
    organisation:
      name: "Metz Numeric School"
    general-group:
      name: "Général"
    admin:
      email: "remyyannick@sfr.fr"
      first-name: "Yannick"
      last-name: "Remy"