# Base de donnees
spring.datasource.url=jdbc:postgresql://localhost:5432/alertmns
spring.datasource.username=alertmns
spring.datasource.password=alertmns
spring.datasource.driver-class-name=org.postgresql.Driver

# Locale
spring.web.locale=en
spring.web.locale-resolver=fixed

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false