alertmns:
  bootstrap:
    enabled: true
    organisation:
      name: "Metz Numeric School"
    general-group:
      name: "Général"
    admin:
      email: "remyyannick@sfr.fr"
      first-name: "Yannick"
      last-name: "Remy"