name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_HOST: "unix:///var/run/docker.sock"
      TESTCONTAINERS_RYUK_DISABLED: "true"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Docker sanity check
        run: docker version

      - name: Build & test
        run: |
          chmod +x mvnw
          ./mvnw -B verify
